# Created with YamlCreate.ps1 v2.4.1 $debug=QUSU.CRLF.7-4-5.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Microsoft.ServiceFabricRuntime
PackageVersion: 10.1.2448.9590
InstallerLocale: en-US
MinimumOSVersion: 10.0.0.0
InstallerType: exe
Scope: machine
InstallerSwitches:
  Silent: /quiet /qn
  SilentWithProgress: /quiet
  Custom: /AcceptEULA
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://download.microsoft.com/download/b/8/a/b8a2fb98-0ec1-41e5-be98-9d8b5abf7856/MicrosoftServiceFabric.10.1.2448.9590.exe
  InstallerSha256: 7E99099C1F32087A9BC688B510ABA286C26C0BFAE4C93378164336491C2765AA
ManifestType: installer
ManifestVersion: 1.6.0
